### ISSUE TITLE
gulp serve error  'Cannot find module 'object-assign'

### ISSUE THREAD

**Issue by danywalls** [slushjs/slush-angular#54]
If install slush-angular with Nodejs version 4.1.2 and gulp already installed , i got this the follow error:

``` bash
danyAir:app danyparedes$ gulp serve
module.js:339
    throw err;
    ^

Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/gulp-util/lib/PluginError.js:5:20)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by danywalls** [comment]
This issue has been update nodejs version to 4.2.1 and reinstalling gulp.
