### ISSUE TITLE
bug after installing and running

### ISSUE THREAD

**Issue by bk-software** [slushjs/slush-angular#58]
node version v16.13.0
os: mac 

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (/usr/local/lib/node_modules/slush/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/slush/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/slush/node_modules/graceful-fs/fs.js:1:37)

**Comment by joakimbeng** [comment]
The slush-angular generator is really old and for AngularJS not Angular, despite its name, so you shouldn't be using it.
If you want to initialise a new Angular project there are better and more up to date ways of doing so. https://angular.io/ is a good place to start.
